# Get the number of terms from the user
n = int(input("Enter the number of terms in Fibonacci series: "))

# First two terms
a, b = 0, 1
count = 0

# Check if the number of terms is valid
if n <= 0:
    print("Please enter a positive integer.")
elif n == 1:
    print("Fibonacci series up to 1 term:")
    print(a)
else:
    print("Fibonacci series:")
    while count < n:
        print(a, end=" ")
        a, b = b, a + b
        count += 1
# Fibonacci series is generated by adding the two previous terms to get the next term.
# Example: 0, 1, 1, 2, 3, 5, 8, 13, ...